name: Deploy Workflow

on:
  workflow_call:
    inputs:
      tfVersion:
        required: true
        type: string
    outputs:
     terraformVersion:
      description: "The first output string"
      value: ${{ jobs.deploy.outputs.output1 }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.terraformVersion }}
    
    steps:
      - name: terraform
        run: |
             TERRAFORM_VERSION="${{ inputs.tfVersion }}"
              wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform --version
      - name: Deploy code
        id: step1
        run: |
             terraformVersion=$( terraform.exe -v | grep Terraform | head -n 1)
             echo "firstword=hello" >> $GITHUB_OUTPUT
