name: Workflow Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

            
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - id: fiestouofrsacfad
        if: ${{needs.job1.outputs.output1 == "hello" }}
        run: |
              echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - name: chekcing
        run: echo "third step"
  #- name: antohter workdlow
#     uses: SuprajMaripeddi/github_actions_terraform/.github/workflows/calling.yaml@new
#     with:
#       environment: dev
      # - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
     #   my_output: ${{ steps.set_output_value.outputs.my_output }}
#    my-workflow-job-2:
#         if: ${{ hello_world.outputs.my_output == 'hello worldsss' }}
#         uses: SuprajMaripeddi/github_actions_terraform/.github/workflows/calling.yaml@new
#         with:
#           environment: dev
        #secrets: inherit
