name: Deploy Workflow

on:
  workflow_call:
    inputs:
      tfVersion:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: terraform
        run: |
             TERRAFORM_VERSION="${{ inputs.tfVersion }}"
              wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform --version
      - name: Deploy code
        run: |
          if [ "${{ inputs.tfVersion }}" = "production" ]; then
            echo input is  production
          else
            echo input is not  production 
          fi
