name: Workflow Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
      - id: step3
        run: | 
                echo "YYYYYYYYYYYYYYY"
                echo '${{ secrets.MY_SECRET }}'
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
    ##############2orking code 
#     steps:
#       - id: fiestouofrsacfad
#         if: ${{ contains(needs.job1.outputs.output1, 'hello') }}
#       #  if: ${{needs.job1.outputs.output1 == "hello" }}
#         run: |
#               echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
#       - name: chekcing
#         run: echo "third step"
#####    ##############2orking code 
  terraform_apply:
    needs: job1
    if: ${{ contains(needs.job1.outputs.output1, 'nothello') }}
    uses: SuprajMaripeddi/github_actions_terraform/.github/workflows/calling.yaml@new
    with:
      environment: ${{ inputs.environment }}
    secrets: 
      MY_SECRET: ${{ secrets.MY_SECRET }}
              
              


