name: Workflow Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

            
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
       
        - id: step1
          run: echo "test=hello" >> $GITHUB_OUTPUT
        - name: Set output value
          run: #echo "::set-output name=my_output::hello world"
              echo "hello input ${{ inputs. environment }}"
            
      outputs:
       output1: ${{ steps.step1.outputs.test }}
   job2:
    runs-on: ubuntu-latest
    if:  ${{needs.job1.outputs.output1 == "hello"}}
    needs: job1
    steps:
      - name: antohter workdlowss
        run: echo "job passed"
      - name: antohter workdlow
        uses: SuprajMaripeddi/github_actions_terraform/.github/workflows/calling.yaml@new
        with:
         environment: dev
      # - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
     #   my_output: ${{ steps.set_output_value.outputs.my_output }}
#    my-workflow-job-2:
#         if: ${{ hello_world.outputs.my_output == 'hello worldsss' }}
#         uses: SuprajMaripeddi/github_actions_terraform/.github/workflows/calling.yaml@new
#         with:
#           environment: dev
        #secrets: inherit
